"""add role column to clothes DB

Revision ID: 2e27a6c797c6
Revises: 67ecc6219a05
Create Date: 2023-03-04 14:52:13.515329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e27a6c797c6'
down_revision = '67ecc6219a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    userrolesenum = postgresql.ENUM('super_admin', 'admin', 'user', name='userrolesenum')
    userrolesenum.create(op.get_bind())
    op.add_column('user', sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='userrolesenum'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
